---
- name: Copy and set permissions for .copytest
  hosts: localhost  # You can change the host to your target host
  become: yes

  tasks:
    - name: Copy the folder to /opt/.copytest
      copy:
        src: /home/kali/build-machine/copytest
        dest: /opt/.copytest
        remote_src: yes
        # Use backup to avoid changing the modification time when copying.
        backup: yes

    - name: Set permissions for .copytest directory
      file:
        path: /opt/.copytest
        state: directory
        mode: "0755"  # Readable for all, writeable for root

