- name: Add Microsoft GPG key for VSCode
  become: yes
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Add VSCode repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Update APT package cache
  become: yes
  apt:
    update_cache: yes

- name: Install required packages for mitm6
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3
    - python3-pip

- name: Install mitm6 via pip
  become: yes
  pip:
    name: mitm6

- name: Install VSCode, Terminator, Gobuster, SecLists, ltrace, html2text, and jq
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - code
    - terminator
    - gobuster
    - seclists
    - ltrace
    - html2text
    - jq
    - gh
    - rsh-client